version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  default: all
  disable:
    - wsl
    - copyloopvar
    - intrange
    - gomodguard
    - goconst
    - cyclop
    - depguard
    - dupl
    - forcetypeassert
    - funlen
    - ireturn
    - maintidx
    - nonamedreturns
    - paralleltest
    - varnamelen
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
