run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - structcheck # deprecated
    - nosnakecase # deprecated
    - golint # deprecated
    - varcheck # deprecated
    - exhaustivestruct # deprecated
    - deadcode # deprecated
    - ifshort # deprecated
    - scopelint # deprecated
    - maligned # deprecated
    - varnamelen
    - dupl
    - paralleltest
    - depguard
    - forcetypeassert
    - funlen
    - maintidx
    - cyclop
    - ireturn
