run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - varnamelen
    - dupl
    - paralleltest
    - depguard
    - forcetypeassert
    - funlen
    - maintidx
    - cyclop
    - ireturn
    - execinquery
    - gomnd
    - exportloopref
    - copyloopvar
    - intrange
