run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - scopelint # deprecated
    - varnamelen
    - dupl
    - paralleltest
