run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - scopelint # deprecated
    - nosnakecase # deprecated
    - varcheck # deprecated
    - structcheck # deprecated
    - deadcode # deprecated
    - varnamelen
    - dupl
    - paralleltest
