version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  default: all
  disable:
  - wsl
  - copyloopvar
  - intrange
  - cyclop
  - depguard
  - dupl
  - forcetypeassert
  - funlen
  - nlreturn
  - ireturn
  - maintidx
  - nonamedreturns
  - paralleltest
  - revive
  - varnamelen
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
