language: go

go:
  - 1.12.17
  - 1.13.15
  - 1.14.9
  - 1.15.2
  - tip

script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
